//
//  DineInWebModels.swift
//  Pods
//
//  Created by elad schiller on 8/7/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MyCheckCore


enum AddMasterPass
{
    struct ViewModel{
        let JSToBeInjected: String
    }
    struct FailResponse{
        let error: NSError
        let callback: String
    }
    // MARK: Use cases
    enum Setup {
        struct Request{
            let payload: MasterPassInitPayload
        }
    
    }
    enum GetMasterpassToken
    {
        struct Request
        {
            let callback: String
        }
        
        
        struct Response
        {
            let callback: String
            let payload: MasterPassInitPayload

        }
        
        
    }
    
    enum AddMasterpass
    {
        struct Request
        {
            let complitionStatus: AddMasterPassViewControllerCompletitionReason

        }
        
        
        struct Response
        {
            let complitionStatus: AddMasterPassViewControllerCompletitionReason

        }
        struct ViewModel{
            let complitionStatus: AddMasterPassViewControllerCompletitionReason

        }
        
    }
}



