use_frameworks!
source 'https://bitbucket.org/erez_spatz/pod-spec-repo.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'MyCheckWalletUI_Example' do
    pod 'MyCheckWalletUI/Core'
    #, :path => '../'
#   pod 'MyCheckWalletUI/PayPal', :path => '../'
#   pod 'MyCheckWalletUI/MasterPass', :path => '../'
   pod 'MyCheckWalletUI/ApplePay'
   #, :path => '../'

#    pod 'MyCheckWalletUI/VisaCheckout', :path => '../'
pod 'MyCheckCore', :path => '../../MyCheck-Core'

  target 'MyCheckWalletUI_Tests' do
    inherit! :search_paths
    pod 'MyCheckCore'
    #, :path => '../../MyCheck-Core'

    pod 'MyCheckWalletUI/Core'
    #, :path => '../'
#    pod 'MyCheckWalletUI/PayPal', :path => '../'
#    pod 'MyCheckWalletUI/MasterPass', :path => '../'
    pod 'MyCheckWalletUI/ApplePay'
    #, :path => '../'

    pod 'Quick'
    pod 'Nimble'


  end
end
