use_frameworks!
source 'https://bitbucket.org/erez_spatz/pod-spec-repo.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'MyCheckWalletUI_Example' do
  pod 'MyCheckWalletUI', :path => '../'
   pod 'MyCheckWalletUI/PayPal', :path => '../'

  target 'MyCheckWalletUI_Tests' do
    inherit! :search_paths


  end
end
