use_frameworks!
source 'https://bitbucket.org/eladsc/pod-spec-repo.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'MyCheckWalletUI_Example' do
  pod 'MyCheckWalletUI', :path => '../'

  target 'MyCheckWalletUI_Tests' do
    inherit! :search_paths

   
  
  end
end
