//
//  AddCreditCardPresenter.swift
//  Pods
//
//  Created by elad schiller on 7/23/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddCreditCardPresentationLogic
{
    func presentSubmitFormResponse(response: AddCreditCard.SubmitForm.Response)
    func present
    
    func displayLoadingIndicator(display: Bool)
    

}

class AddCreditCardPresenter: AddCreditCardPresentationLogic
{
  weak var viewController: AddCreditCardDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: AddCreditCard.Something.Response)
  {
    let viewModel = AddCreditCard.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
