//
//  AddCreditCardInteractor.swift
//  Pods
//
//  Created by elad schiller on 7/23/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddCreditCardBusinessLogic
{
    func changeTextInField(request: AddCreditCard.TextChanged.Request)
    func submitForm(request: AddCreditCard.SubmitForm.Request)
    
}

protocol AddCreditCardDataStore
{
    //var name: String { get set }
}

class AddCreditCardInteractor: AddCreditCardBusinessLogic, AddCreditCardDataStore
{
    var presenter: AddCreditCardPresentationLogic?
    var state = AddCreditCard.State.inputingDetails
    var model = AddCreditCard.FormData.init(number: "", date: "", cvv: "", zip: "")
    //var name: String = ""
    
    // MARK: Do something
    
    func changeTextInField(request: AddCreditCard.TextChanged.Request)
    {
        switch request.type{
        case .number(text: text, imageURL: urlStr):
            
            
            
        }
        
    }
}
