//
//  MCCheckoutViewControllerPresenterPresenter.swift
//  Pods
//
//  Created by elad schiller on 8/20/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit



class MCCheckoutViewControllerPresenterPresenter: AddCreditCardPresenter
{
  
 
}
